version: '2.1'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        volumes:
            - .:/app
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 8080:80
        links:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./public:/public
