version: '2.1'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        links:
            - db
        volumes:
            - .:/app
        command: nodemon index.js
        environment:
            STRIPE_SECRET_KEY: sk_test_y0agyth77qhFgBt6OjFWwKRm
            STRIPE_PUBLIC_KEY: pk_test_1F1BAFZH0ChBDlVXGa39i3J9

    db:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: sparkschool
            POSTGRES_DB: sparkschool
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        ports:
            - 5432:5432

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 8080:80
        links:
            - app
        volumes:
            - ./nginx.dev.conf:/etc/nginx/nginx.conf
            - ./public:/public
