redis_port: 6379
redis_host: redis
redis_prefix: sixpack
redis_db: 15

# The regex to match for robots
robot_regex: $^|trivial|facebook|MetaURI|butterfly|google|amazon|goldfire|sleuth|xenu|msnbot|SiteUptime|Slurp|WordPress|ZIBB|ZyBorg|pingdom|bot|yahoo|slurp|java|fetch|spider|url|crawl|oneriot|abby|commentreader|twiceler
ignored_ip_addresses: []                    # List of IP

asset_path: dist                            # Path for compressed assets to live. This path is RELATIVE to sixpack/static
secret_key: 'sixpack-of-pbr'                # Random key (any string is valid, required for sixpack-web to run)
