version: '2.1'
services:
    sixpack:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
        ports:
            - 5000:5000
        command: "sixpack"

    sixpack_web:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
        ports:
            - 80:5001
        command: "sixpack-web"

    redis:
        image: redis:3.2
        volumes:
            - /data:/data
        command: "redis-server --appendonly yes"
