version: '2.1'
services:
    sixpack:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
        ports:
            - 5000:5000
        command: " gunicorn --access-logfile - --error-logfile - -w 8 --worker-class=gevent sixpack.server:start"

    sixpack_web:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
        ports:
            - 80:5001
        command: " gunicorn --access-logfile - --error-logfile - -w 2 --worker-class=gevent sixpack.web:start"

    redis:
        image: redis:3.2
        volumes:
            - /data:/data
        command: "redis-server --appendonly yes"
